apiVersion: apps/v1
kind: Deployment
metadata:
  name: ritual-explorer-fresh
  labels:
    app: ritual-explorer-fresh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ritual-explorer-fresh
  template:
    metadata:
      labels:
        app: ritual-explorer-fresh
    spec:
      containers:
      - name: ritual-explorer
        image: gcr.io/testing-logging-2/ritual-explorer:4eec959-20250929-080912
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_DEFAULT_CHAIN
          value: "ethereum"
        - name: NEXT_PUBLIC_RETH_RPC_URL
          value: "http://35.185.40.237:8545"
        - name: NEXT_PUBLIC_RETH_WS_URL
          value: "ws://35.185.40.237:8546"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ritual-explorer-fresh-service
  labels:
    app: ritual-explorer-fresh
spec:
  selector:
    app: ritual-explorer-fresh
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ritual-explorer-fresh-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ritual-explorer-fresh
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
