apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ws-proxy-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        # WebSocket proxy upstream
        upstream rpc_websocket {
            server 35.196.101.134:8546;
        }
        
        server {
            listen 8546;
            server_name ws.ding.fish;
            
            location / {
                proxy_pass http://rpc_websocket;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_read_timeout 86400;
                proxy_send_timeout 86400;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ws-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ws-proxy
  template:
    metadata:
      labels:
        app: nginx-ws-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8546
          name: websocket
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-ws-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ws-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.27.235.176
  selector:
    app: nginx-ws-proxy
  ports:
  - name: websocket
    port: 8546
    targetPort: 8546
    protocol: TCP

