apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-proxy-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream rpc_websocket {
            server 35.196.101.134:8546;
        }
        
        server {
            listen 8546;
            
            location / {
                proxy_pass http://rpc_websocket;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_read_timeout 86400;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ws-proxy
  template:
    metadata:
      labels:
        app: ws-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8546
          name: websocket
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: nginx-config
        configMap:
          name: ws-proxy-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: ws-proxy-service
  annotations:
    cloud.google.com/backend-config: '{"default": "ws-proxy-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: ws-proxy
  ports:
  - name: websocket
    port: 8546
    targetPort: 8546
    protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ws-proxy-backend-config
spec:
  timeoutSec: 86400  # 24 hours for WebSocket
  connectionDraining:
    drainingTimeoutSec: 60

