apiVersion: v1
kind: Service
metadata:
  name: caddy-ws-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.27.235.176
  selector:
    app: caddy-ws-proxy
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400

